### ISSUE TITLE
Files with Different Number of Lines

### ISSUE THREAD

**Issue by ShirleyHan6** [pltrdy/files2rouge#28]
Hi Pltrdy!

Do you know of any python ROUGE calculator that supports it if files have different number of lines? 

Thanks!
Shirley

**Comment by pltrdy** [comment]
Hmm. I'm not sure what do you want to calculate. I mean, to get score you need to have hypothesis and references. On this repo we suppose that one file contains all hypothesis (1 by line) and the other contains all references (1 by line). This would not make sense to have a different number of lines, because then what score do you calculate?

I you consider one file as the whole hypothesis text, and the other as the whole reference text, then you can just concatenate it into 1 single line and use this repo.

**Comment by ShirleyHan6** [comment]
Ok I got what you meant! Thanks for explaining!
